"""add_celery_task_id_to_reminders

Revision ID: 122b0945b5a7
Revises: 14b01d29025a
Create Date: 2026-03-30 00:35:35.639082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122b0945b5a7'
down_revision: Union[str, Sequence[str], None] = '14b01d29025a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('celery_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'celery_task_id')
    # ### end Alembic commands ###
